# Generated by Django 6.0.3 on 2026-04-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flightsco_app", "0002_seed_flight_articles"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Категория перелетов",
                "verbose_name_plural": "Категории перелетов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FlightTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Название тега"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Тег предложения",
                "verbose_name_plural": "Теги предложений",
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="flightarticle",
            new_name="flightsco_a_time_cr_320ccf_idx",
            old_name="flightsco_a_time_cr_6c217f_idx",
        ),
        migrations.RenameIndex(
            model_name="flightarticle",
            new_name="flightsco_a_status_7016f1_idx",
            old_name="flightsco_a_status_77f33b_idx",
        ),
        migrations.AddField(
            model_name="flightarticle",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="flightsco_app.flightcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="flightarticle",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="flightsco_app.flighttag",
                verbose_name="Теги",
            ),
        ),
    ]
