# Generated by Django 6.0.3 on 2026-04-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flightsco_app", "0005_alter_flightarticle_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="uploads_model/", verbose_name="Файл"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Загруженный файл",
                "verbose_name_plural": "Загруженные файлы",
                "ordering": ["-time_create"],
            },
        ),
        migrations.AddField(
            model_name="flightarticle",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Фото предложения",
            ),
        ),
    ]
